<a href="https://colab.research.google.com/github/yazid711/TugamDM/blob/main/DataMining/TugasDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ini untuk menampilkan semua data jika yang di cetak x maka yang akan muncul itu semua data kecuali label sedangkan jika yang di cetak itu y maka yang muncul hanyalah label saja


In [ ]:
dataset = pd.read_csv('TugasDM.csv')
dataset = pd.read_csv('TugasDM.csv', sep =';')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

ini tabelnya

In [ ]:
print (x)

[['Dokter' 40.0 nan]
 ['Guru' 33.0 2300000.0]
 ['Dokter' 45.0 5000000.0]
 ['Progammer' 23.0 4000000.0]
 ['Dokter' nan 4500000.0]
 ['Guru' 28.0 1500000.0]
 ['Insinyur' 18.0 3000000.0]
 ['Insinyur' 55.0 7000000.0]
 ['Insinyur' 41.0 5300000.0]
 ['Dokter' 57.0 6700000.0]]


ini labelnya

In [ ]:
print (y)

['High' 'Medium' 'High' 'Medium' 'High' 'Low' 'Medium' 'High' 'High'
 'High']


ini untuk mengisi tabel yang nan

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Dokter' 40.0 4366666.666666667]
 ['Guru' 33.0 2300000.0]
 ['Dokter' 45.0 5000000.0]
 ['Progammer' 23.0 4000000.0]
 ['Dokter' 37.77777777777778 4500000.0]
 ['Guru' 28.0 1500000.0]
 ['Insinyur' 18.0 3000000.0]
 ['Insinyur' 55.0 7000000.0]
 ['Insinyur' 41.0 5300000.0]
 ['Dokter' 57.0 6700000.0]]


ini untuk merubah kolom pertama menjadi numerik

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 40.0 4366666.666666667]
 [0.0 1.0 0.0 0.0 33.0 2300000.0]
 [1.0 0.0 0.0 0.0 45.0 5000000.0]
 [0.0 0.0 0.0 1.0 23.0 4000000.0]
 [1.0 0.0 0.0 0.0 37.77777777777778 4500000.0]
 [0.0 1.0 0.0 0.0 28.0 1500000.0]
 [0.0 0.0 1.0 0.0 18.0 3000000.0]
 [0.0 0.0 1.0 0.0 55.0 7000000.0]
 [0.0 0.0 1.0 0.0 41.0 5300000.0]
 [1.0 0.0 0.0 0.0 57.0 6700000.0]]


ini merubah label menjadi numerik

In [ ]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
y = Le.fit_transform(y)

In [ ]:
print(y)

[0 2 0 2 0 1 2 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, = train_test_split(x, y, test_size = 0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 0.0 18.0 3000000.0]
 [1.0 0.0 0.0 0.0 37.77777777777778 4500000.0]
 [1.0 0.0 0.0 0.0 40.0 4366666.666666667]
 [0.0 0.0 0.0 1.0 23.0 4000000.0]
 [0.0 1.0 0.0 0.0 33.0 2300000.0]
 [0.0 0.0 1.0 0.0 55.0 7000000.0]
 [0.0 0.0 1.0 0.0 41.0 5300000.0]
 [0.0 1.0 0.0 0.0 28.0 1500000.0]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 0.0 45.0 5000000.0]
 [1.0 0.0 0.0 0.0 57.0 6700000.0]]


In [ ]:
print(y_train)

[2 0 0 2 2 0 0 1]


In [ ]:
print(y_test)

[0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.3779644730092272 -1.5096195396677181 -0.6115292616180796]
 [1.0 0.0 0.0 -0.3779644730092272 0.3029422010463045 0.309602680568149]
 [1.0 0.0 0.0 -0.3779644730092272 0.5066008235984418 0.22772428570715106]
 [0.0 0.0 0.0 2.6457513110645903 -1.051387638925409 0.002558699839406095]
 [0.0 1.0 0.0 -0.3779644730092272 -0.13492383744079095
  -1.0413908346383196]
 [0.0 0.0 1.0 -0.3779644730092272 1.881296525825369 1.8448225842118633]
 [0.0 0.0 1.0 -0.3779644730092272 0.5982472037469037 0.8008730497341375]
 [0.0 1.0 0.0 -0.3779644730092272 -0.5931557381831001 -1.5326612038043084]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 -0.3779644730092272 0.9648327243407508 0.6166466612968918]
 [1.0 0.0 0.0 -0.3779644730092272 2.0645892861222928 1.6605961957746176]]
